// Single source of truth → (1) app theme CSS vars, (2) Python-report CSS vars.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const t = JSON.parse(readFileSync(`${root}/design/brass-editorial.tokens.json`, 'utf8'));

const vars = (obj) => Object.entries(obj).map(([k, v]) => `  --${k}: ${v};`).join('\n');
const radius = Object.entries(t.radius).map(([k, v]) => `  --radius-${k}: ${v};`).join('\n');
const fonts = `  --font-display: ${t.font.display};\n  --font-body: ${t.font.body};\n  --font-mono: ${t.font.mono};`;

const css =
`/* GENERATED by design/emit-tokens.mjs — do not edit by hand. */
:root {
${fonts}
${radius}
${vars(t.color.light)}
}
.dark {
${vars(t.color.dark)}
}
`;

for (const out of [`${root}/app/src/styles/tokens.css`, `${root}/design/brass-editorial.vars.css`]) {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, css);
  console.log('wrote', out);
}
